vocab_dir: ./libs/storage/vocab_dataset.json
service:
  checkpoint_dir: ./saved_model/best.pth
pre_trained_model: nguyenvulebinh/wav2vec2-base-vietnamese-250h
rate: 16000
vmd_model:
  best_checkpoint:
    data_name: test
    metric_type: f1_score
  best_score: 0.58
  best_seed: 42
  checkpoint_dir: ./saved_model/best_not_aug.pth
  decoder:
    feed_forward:
      dropout: 0.1
    mha:
      dropout: 0.1
      num_heads: 4
  early_stopping:
    data_name: test
    loss_type: loss
    patience: 5
  epoch_num: 80
  linguistic_encoder:
    drop_out: 0.1
    embs_dim: 768
    embs_type_dim: 256
    hidden_size: 384
    input_size: 768
    num_types: 6
  lr: 0.0002
  n_train: 1
  num_classes: 124
  phonetic_encoder:
    drop_out: 0.1
    hidden_size: 384
    input_size: 768
