# Extract Features

embs_dim: 768
embs_type_dim: 256
embs_mispro_dim: 256

#RNN Parameters
rnn_layers: 1
rnn_input_size: 768
rnn_hidden_size: 768
rnn_type: "nn.LSTM"
rnn_bidirectional: True
rnn_batch_first: False
rnn_drop_out: 0.1
