# Training paramaters

#Dataset
dev_split: 0.2 # Nếu valid set là train_dataset split
valid_set_is_test_set: True

use_gpu: True
init_lr: 0.0001
num_epoches: 100
adjust_lr_diff_value: 2
lr_decay: 0.75
batch_size: 16
weight_decay: 0.0005
seed: 80
shuffle: True

# Path
vocab_path: "../speech_dataset/phoneme.txt"
a_param_path: "../config/acoustic_param.yaml"
pi_param_path: "../config/pitch_param.yaml"
p_param_path: "../config/phonetic_param.yaml"
l_param_path: "../config/linguistic_param.yaml"
training_path: "../config/training_param.yaml"

csv_path_train: "../speech_dataset/train_phones.csv"
csv_path_public_test: "../speech_dataset/test_phones.csv"
csv_path_private_test: "../speech_dataset/private_test_phones.csv"
path_save_data_public_test: "../speech_dataset/data_public_test.pth"
path_save_data_private_test: "../speech_dataset/data_private_test.pth"
path_save_data_train: "../speech_dataset/data_train.pth"

path_save_data_public_test_augment: "../speech_dataset/data_public_test_augment.pth"
path_save_data_private_test_augment: "../speech_dataset/data_private_test_augment.pth"
path_save_data_train_augment: "../speech_dataset/data_train_augment.pth"